name: Run avenue-server tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          cache: maven
      - name: Build and test
        run: mvn -B clean verify

  publish:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          cache: maven
      - name: Prepare artifact
        run: |
          mvn --batch-mode --update-snapshots package
          mkdir -p staging
          cp target/*.jar staging/
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
